#!/bin/sh
clear
set -x
cd ~ || exit 1

sudo apt install curl neovim vim || exit 1

# Just curl down the .vimrc and init.lua
curl -O https://codeberg.org/knyz/vilyaemsetup/raw/branch/master/stow/vim/.vimrc || exit 1
mkdir -p ~/.config/nvim/ || exit 1
cd ~/.config/nvim/ || exit 1
curl -O https://codeberg.org/knyz/vilyaemsetup/raw/branch/master/stow/nvim/.config/nvim/init.lua

cd ~ || exit 1

printf "Vilyaem's neovim + vim setup have been installed\n"
