# Backend
backend = "glx";
vsync = true;

# Enable shadows
shadow = false;
shadow-radius = 48;
shadow-offset-x = -10;
shadow-offset-y = -10;
shadow-opacity = 0.9;
shadow-exclude = [
  "class_g = 'Dmenu'",
  "class_g = 'Polybar'",
  "class_g = 'Conky'",
  "name = 'Notification'",
  "class_g = 'LibreWolf' && argb",
  "class_g = 'slop'"
];

# Fading
fading = true;
fade-in-step = 0.06;
fade-out-step = 0.05;
fade-delta = 10;

# Transparency
inactive-opacity = 0.90;
active-opacity = 1.0;
frame-opacity = 0.9;
inactive-opacity-override = true;
blur-background = true;

# Blur settings (Aero style)
blur-method = "dual_kawase";
blur-strength = 5;
blur-background-exclude = [
  "window_type = 'dock'",
  "window_type = 'desktop'",
  "window_type = 'librewolf'",
  "_NET_WM_STATE@:32a *= '_NET_WM_STATE_FULLSCREEN'"
];

# Rounded corners (optional, adjust radius)
# corner-radius = 12;
# rounded-corners-exclude = [
#   "class_g = 'Dmenu'",
#   "class_g = 'LibreWolf'",
#   "window_type = 'dock'",
#   "window_type = 'desktop'"
#   "class_g = 'Dmenu'",
#   "class_g = 'Polybar'",
#   "class_g = 'Conky'",
#   "name = 'Notification'",
#   "class_g = 'LibreWolf' && argb",
#   "class_g = 'slop'"
# ];

# Use X Sync for tear-free rendering
use-damage = false;

# Avoid drawing over fullscreen
unredir-if-possible = true;

# Experimental backends (for newer systems)
#use-damage = false;

