# Vilyaem's Tmux

# Default shell is zsh
set-option -g default-shell /bin/zsh
#set-option -g default-shell /bin/fish # for fun

# Colors
set -g pane-border-style fg=grey
set -g pane-active-border-style "bg=default fg=lightblue"
set -g status-bg blue
set -g status-fg black

set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*:Tc"
set -g status-style bg=default
set -g status-position top


# Enable mouse
set -g mouse on

# Enable VI mode keys
setw -g mode-keys vi

# Index at 1 instead of 0
set -g base-index 1
setw -g pane-base-index 1

# Different prefix key Ctrl-b -> Ctrl-a
set -g prefix C-a

# File reloading
bind r source-file ~/.config/tmux/tmux.conf \;

# Close immediately
unbind x
bind x kill-pane
bind X kill-session

# More window splitting
bind | split-window -h
bind - split-window -v

# Clipboard
set-option -g set-clipboard on
bind-key -T copy-mode-vi y send -X copy-pipe-and-cancel "xclip -selection clipboard -in"

# Sending and joining panes
bind-key j command-prompt -p "join pane from:"  "join-pane -s '%%'"
bind-key s command-prompt -p "send pane to:"  "join-pane -t '%%'"
