export PATH="$HOME/.local/bin:$PATH"
[ -f "$HOME/.profile" ] && . "$HOME/.profile"
[ -f "$HOME/.nix-profile/etc/profile.d/nix.sh" ] && \
  . "$HOME/.nix-profile/etc/profile.d/nix.sh"
$HOME/.local/bin/bar &
xset r rate 300 100 &
picom &
setxkbmap -option caps:escape us dvorak &
xbanish &
redshift  &2
xinput set-prop "Elan Touchpad" "libinput Tapping Enabled" 1 &
xinput set-prop "Logitech USB Optical Mouse" "libinput Accel Profile Enabled" 0, 1 &
clipmenud &
find "$HOME/w" -name '*.jpg' | shuf -n 1 | xargs xwallpaper --stretch &
autocutsel -fork
autocutsel -selection PRIMARY -fork
xset s 300
xss-lock --transfer-sleep-lock -- slock &
aw-server & 
a|w-watcher-afk & 
aw-watcher-window & 
nhkd &
exec dwm
#exec dbus-launch --exit-with-session exec dwm
#exec $1
