[flavor]
dark = "obsidian-soft-glow"

[app]
overall = { bg = "#0A0A0D" }

[mgr]
cwd = { fg = "#5DDFFB", bold = true }

find_keyword  = { fg = "#FFD479", bold = true, italic = true, underline = true}
find_position = { fg = "#D8D8D8", bg = "reset", bold = true, italic = true}

marker_copied   = { fg = "#32B6BD", bg = "#32B6BD" }
marker_cut      = { fg = "#C44A32", bg = "#C44A32" }
marker_marked   = { fg = "#5DDFFB", bg = "#5DDFFB" }
marker_selected = { fg = "#9E97CE", bg = "#9E97CE" }

count_copied   = { fg = "#0A0A0D", bg = "#32B6BD" }
count_cut      = {fg = "#0A0A0D", bg = "#C44A32"} 
count_selected = {fg = "#0A0A0D", bg = "#9E97CE"}

border_symbol = "┃"
border_style  = { fg = "#1A1A22", bold= true}

symlink_target = {fg = "#9E97CE", italic = true}

[indicator]
parent  = { fg = "#A8A8C0", bg = "#121217" }
current = { fg = "#FF9F40", bg = "#0E0E11", bold = true}
preview = { fg = "#E86A4A", bg = "#14141A" }

padding = { open = "█", close = "█" }

[mode]
normal_main = {fg = "#0A0A0D", bg = "#E86A4A", bold = true}
normal_alt = {fg = "#5DDFFB", bg = "#121217"}

select_main = {fg = "#0A0A0D", bg = "#5DDFFB", bold = true}
select_alt = {fg = "#E86A4A", bg = "#121217"}

unset_main = {fg = "#0A0A0D", bg = "#9E97CE"}
unset_alt = {fg ="#9E97CE", bg ="#121217"}

[tabs]
active   = { fg = "#0A0A0D", bg = "#E86A4A", bold = true }
inactive = { fg = "#A8A8C0", bg = "#121217" }

sep_inner = { open = " ", close = " " }
sep_outer = { open = " ", close = " " }

[status]
overall = { fg = "#A8A8C0", bg = "#121217" }

sep_left  = { open = " ", close = " " }
sep_right = { open = " ", close = " " }

perm_type  = { fg = "#E86A4A" }
perm_read  = { fg = "#32B6BD" }
perm_write = { fg = "#FFD479" }
perm_exec  = { fg = "#D97A8C" }
perm_sep   = { fg = "#5A5A6A" }

progress_label  = { fg = "#E86A4A", bold = true }
progress_normal = { fg = "#E86A4A", bg = "#1A1A22" }
progress_error  = { fg = "#D97A8C", bg = "#1A1A22", bold = true }

[which]
cols = 2
mask = { bg = "#0A0A0D" }

cand = { fg = "#E86A4A", bold = true }
rest = { fg = "#A8A8C0" }
desc = { fg = "#D8D8D8" }

separator       = " → "
separator_style = { fg = "#5A5A6A" }

[confirm]
border = { fg = "#1A1A22" }
title  = { fg = "#E86A4A", bold = true }
body   = { fg = "#D8D8D8" }
list   = { fg = "#D8D8D8" }

btn_yes = { fg = "#0A0A0D", bg = "#E86A4A", bold = true }
btn_no  = { fg = "#D8D8D8", bg = "#1A1A22" }

btn_labels = ["Yes", "No"]

[spot]
border   = { fg = "#1A1A22" }
title    = { fg = "#E86A4A", bold = true }
tbl_col  = { fg = "#9E97CE", bold = true }
tbl_cell = { fg = "#D8D8D8" }

[notify]
title_info  = { fg = "#5DDFFB", bold = true }
title_warn  = { fg = "#FFD479", bold = true }
title_error = { fg = "#D97A8C", bold = true }

[pick]
border   = { fg = "#1A1A22" }
active   = { fg = "#0A0A0D", bg = "#E86A4A", bold = true }
inactive = { fg = "#D8D8D8", bg = "#0A0A0D" }

[input]
border   = { fg = "#1A1A22" }
title    = { fg = "#E86A4A", bold = true }
value    = { fg = "#E86A4A" }
selected = { fg = "#0A0A0D", bg = "#E86A4A", bold = true }

[cmp]
border   = { fg = "#1A1A22" }
active   = { fg = "#0A0A0D", bg = "#E86A4A", bold = true }
inactive = { fg = "#D8D8D8", bg = "#0A0A0D" }

icon_file    = ""
icon_folder  = ""
icon_command = ""

[tasks]
border  = { fg = "#1A1A22" }
title   = { fg = "#E86A4A", bold = true }
hovered = { fg = "#0A0A0D", bg = "#E86A4A", bold = true }

[help]
on      = { fg = "#FF9F40", bold = true }
run     = { fg = "#32B6BD" }
desc    = { fg = "#D8D8D8" }
hovered = {  bg = "#0E0E11", bold = true}
footer  = { fg = "#9E97CE" }

icon_info  = ""
icon_warn  = ""
icon_error = ""

[filetype]
rules = [
  # MEDIA
  { mime = "image/*",        fg = "#5DDFFB" },
  { mime = "video/*",        fg = "#9E97CE" },
  { mime = "audio/*",        fg = "#32B6BD" },

  # ARCHIVES
  { mime = "application/*tar*", fg = "#CFA66A" },
  { mime = "application/*zip*", fg = "#CFA66A" },
  { mime = "application/*7z*", fg = "#CFA66A" },
  { mime = "application/*{lzop,lzma,xz,zstd}", fg = "#CFA66A" },
  { url = "*.{cpio,rpm,apk,whl,iso,lz4}", fg = "#CFA66A" },
  { url = "*.{br,Z,snappy}", fg = "#CFA66A" },

  # CODE
  { url = "*.rs", fg = "#5DDFFB" },
  { url = "*.py", fg = "#5DDFFB" },
  { url = "*.{mjs,js,jsx,cjs,clj,cljs}", fg = "#5DDFFB" },
  { url = "*.{ts,tsx}", fg = "#5DDFFB" },
  { url = "*.lua", fg = "#5DDFFB" },
  { url = "*.go", fg = "#5DDFFB" },
  { url = "*.{bash,sh,zsh,fish,ps1,bat,psm1,psd1}", fg = "#5DDFFB" },
  { url = "*.{c,cpp,h}",  fg = "#5DDFFB" },
  { url = "*.{java,kt,kts,scala}",  fg = "#5DDFFB" },
  { url = "*.{rb,cs,php}",  fg = "#5DDFFB" },
  { url = "*.{swift,svelte,vue}",  fg = "#5DDFFB" },
  { url = "*.{r,jl,dart,hs}",  fg = "#5DDFFB" },

  # CONFIG / DATA
  { url = "*.{json,conf,cfg,ini,toml,yaml,yml,xml,plist}", fg = "#9E97CE" },

  # DOCUMENTS
  { url = "*.{wiki,rss,atom,ppt,pptx,docs,epub,mobi,rst,md,adoc,tex,pdf,html,htm,css,scss,sass,less,stylus,ejs,jinja,mustache,hbs}",  fg = "#FFD479" },

  # SPECIAL
  { mime = "inode/empty", fg = "#32B6BD" },
  { url = "*", is = "orphan", fg = "#8A8FA6", bold = true },
  # EXECUTABLES
  { url = "*", is = "exec", fg = "#D97A8C", bold = true },

  # FALLBACKS
  { url = "*/", fg = "#E86A4A" },
  { url = "*",  fg = "#D8D8D8" },
]
[icon]
prepend_dirs = [
  { name = "Downloads", text = "", fg = "#5DDFFB" },
]

append_exts = [
  { name = "mp3", text = "", fg = "#E86A4A" },
  { name = "mp4", text = "", fg = "#9E97CE" },
]
